export enum ParkingSpotType {
    BASIC_PARKING_TYPE = "BASIC_PARKING_TYPE",
    SPECIAL_PARKING_TYPE = "SPECIAL_PARKING_TYPE",
    INCLUSIVE_PARKING_TYPE = "INCLUSIVE_PARKING_TYPE"
}


// export enum ParkingSpotStatus {
//     UNDEFINED_PARKING_LOT_STATUS = "UNDEFINED_PARKING_LOT_STATUS", //white
//     AVAILABLE_PARKING_LOT_STATUS = "AVAILABLE_PARKING_LOT_STATUS", // green
//     BOOKED_PARKING_LOT_STATUS = "BOOKED_PARKING_LOT_STATUS", // grey
//     BOOKED_BY_ME_PARKING_LOT_STATUS = "BOOKED_BY_ME_PARKING_LOT_STATUS", // blue
//     BLOCKED_LOT_STATUS = "BOOKED_BY_ME_PARKING_LOT_STATUS" // red
// }